### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by arnedesmedt** [inspector-apm/inspector-symfony#28]
When inspector tries to serialize the envelope. It throws an exception because it's trying to serialize a closure.

```json
"class": "Exception",
    "message": "Serialization of 'Closure' is not allowed",
    "code": 0,
    "file": "/var/www/vendor/inspector-apm/inspector-symfony/src/Listeners/MessengerEventsSubscriber.php:77",
```

It happens here: https://github.com/inspector-apm/inspector-symfony/blob/master/src/Listeners/MessengerEventsSubscriber.php#L77

I don't know how it could be solved. Maybe just remove that line? But then we don't have any envelope context...

**Comment by pesseyjulien** [comment]
I had the same issue : https://github.com/symfony/symfony/issues/32312

Stopped using the solution for now

**Comment by ilvalerione** [comment]
This error is due to the experimental feature related to the monitoring of the messenger component. Since it will be on the table for the next version of the library I disabled this component.

The latest 1.1.3 shouldn't cause this error anymore. Let me know for any issue.
