### ISSUE TITLE
Ignoring route cause Exception

### ISSUE THREAD

**Issue by pesseyjulien** [inspector-apm/inspector-symfony#29]
Hi,  

 if I put 'admin_index' in ignore_routes then I get an exception (see enclosed). 

Any idea why ?

![Capture d’écran 2022-01-30 à 11 33 42](https://user-images.githubusercontent.com/10850944/151857421-a807b0fa-1bd1-4ef9-81c0-321ca262d09e.jpg)

**Comment by ilvalerione** [comment]
It could be fixed in the latest release.

`currentTransaciton()` method was deprecated in the base library. The symfony bundle is now updated to the last api.
