### ISSUE TITLE
documentation error: ignore_urls / ignore_routes, request for ignore_urls_pattern

### ISSUE THREAD

**Issue by tacman** [inspector-apm/inspector-symfony#38]
https://docs.inspector.dev/guides/symfony/configuration#ignore-urls

Those are routes, not urls.  And indeed in the configuration the key should be `ignore_routes:`

It would nice, though, if ignore_urls existed and could be configured with wildcards.

**Comment by tacman** [comment]
It seems like it'd be pretty easy to add ignore_urls to the config and then check them in the KernelEventSubscriber:

```php
    protected function isRequestEligibleForInspection(KernelEvent $event): bool
    {
        $path = $event->getRequest()->getPathInfo();
        foreach ($this->ignoredPaths as $pathRegex) {
            if (preg_match($pathRegex, $path)) {
                // exclude this url from record
            }
        }
```

**Comment by ilvalerione** [comment]
Hi Tac, it is now supported in the latest package version [1.3.0](https://github.com/inspector-apm/inspector-symfony/releases/tag/1.3.0). I sent you an email with more details.
