### ISSUE TITLE
add option to purge logs

### ISSUE THREAD

**Issue by tacman** [inspector-apm/inspector-symfony#43]
I'd like to be able to purge all logs without deleting the application and re-recreating a new one. In particular, when I push a new version and I'm actively monitoring activity, I don't want the previous results.

Maybe a purge transactions option from the apps page, above Delete?

![image](https://github.com/user-attachments/assets/2c7189e4-4e08-4cb5-bcdb-237a48803435)

**Comment by ilvalerione** [comment]
it's not possible due to internal constraints.
